# Generated by Django 4.0.4 on 2022-04-27 06:55

import digital_plug_2.main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('Illustration', 'Illustration'), ('Typography', 'Typography'), ('Logos', 'Logos')], max_length=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/', validators=[digital_plug_2.main.validators.MaxFileSizeInMbValidator(5)])),
            ],
        ),
    ]
