# Generated by Django 4.0.4 on 2022-04-27 09:21

import digital_plug_2.main.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), digital_plug_2.main.validators.validate_only_letter])),
                ('last_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), digital_plug_2.main.validators.validate_only_letter])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), digital_plug_2.main.validators.validate_only_letter])),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[digital_plug_2.main.validators.MaxFileSizeInMbValidator(5)])),
            ],
        ),
    ]
