# Generated by Django 4.0.4 on 2022-04-27 21:12

import digital_plug_2.main.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_category_project_creator_remove_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[digital_plug_2.main.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
