# Generated by Django 4.0.4 on 2022-04-28 12:15

import digital_plug_2.main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_creator_user_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, default='user-filled-shape.png', null=True, upload_to='profiles/', validators=[digital_plug_2.main.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
