# Generated by Django 4.0.4 on 2022-04-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_creator_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='email',
        ),
    ]
